/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component, useState, useRef, useEffect } from 'react';
import { View, Image, Text, PixelRatio, ScrollView, TouchableOpacity, Animated } from 'react-native';
import { Storyly } from 'storyly-react-native';


const PIN_ICON = require('./assets/pin_icon.png');


const STORYLY_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NfaWQiOjU1NiwiYXBwX2lkIjoxMzg5LCJpbnNfaWQiOjE4NjY1fQ._PwkZ48JdHkSU01KUR2n66zJcL29JhykNTMRUorfvE4"

export default class App extends Component {
    constructor(props) {
        super(props);

        this.state = {
            uniqueKey: 0,
            isHidden: true,
        };
    }

    render() {
        return (
            <View>
                <ScrollView>
                    <Storyly
                        key={this.state.uniqueKey}
                        ref={ ref => {
                            this.storyly = ref;
                        }}
                        style={{ width: '100%', height: 120, marginTop: 10, backgroundColor: "#7fff00" }}
                        storylyId={"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NfaWQiOjU1NiwiYXBwX2lkIjoxMzg5LCJpbnNfaWQiOjE4NjY1fQ._PwkZ48JdHkSU01KUR2n66zJcL29JhykNTMRUorfvE4"}
                        onLoad={() => {
                            this.storyly.openStoryWithId("116847");
                        }} 
                        onStorylyStoryPresented={() => {
                            this.state.uniqueKey += 1
                        }} />
                </ScrollView>
            </View>
        );
    }
}

const convertToNative = (size) => {
    return Platform.OS === 'android' ? PixelRatio.getPixelSizeForLayoutSize(size) : size
}


const CustomPortraitView = ({ storyGroup }) => {
    return (
        <>
            {(storyGroup ? (
                <View style={{ width: 100, height: 178 }}>
                    <Image style={{
                        width: "100%",
                        height: "100%",
                        borderRadius: 8
                    }}
                        source={{ uri: storyGroup.iconUrl }} />
                    <View style={{ width: 100, height: 168, borderRadius: 8, position: 'absolute', backgroundColor: storyGroup.seen ? "#16ad055f" : "#1905ad5f" }}>
                        <View style={{ flexDirection: 'column', width: 90, marginTop: 20, marginLeft: 5, height: "100%", alignItems: 'center', justifyContent: 'flex-start' }}>
                            {storyGroup.pinned ?
                                <Image style={{ width: 20, height: 20, marginTop: 5, marginBottom: 10, borderRadius: 10 }} source={PIN_ICON} /> : <View style={{ width: 20, height: 20, marginTop: 5, marginBottom: 10 }} />}
                            <Text style={{ flexWrap: 'wrap', width: "90%", textAlign: 'center', fontWeight: 'bold', fontSize: 15, color: "white" }}>{storyGroup.title}</Text>
                        </View>
                    </View>
                </View>
            ) : (
                <View style={{ width: "100%", height: "100%", borderRadius: 8 }}></View>
            ))}
        </>
    )
}


const ShowHideAnimation = (props) => {
    const heightAnim = useRef(new Animated.Value(0)).current;

    useEffect(() => {
        Animated.timing(heightAnim, {
            toValue: props.isHidden ? 0 : props.style.height,
            duration: 500,
            useNativeDriver: false,
        }).start();
    }, [props.isHidden])

    return (
        <Animated.View style={{ height: heightAnim, overflow: 'hidden' }}>
            {props.children}
        </Animated.View>
    );
};
