/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component, useState, useRef, useEffect } from 'react';
import { Dimensions, View, Image, Text, StyleSheet, PixelRatio, ScrollView, TouchableOpacity, Animated } from 'react-native';
import { Storyly } from 'storyly-react-native';


const PIN_ICON = require('./assets/pin_icon.png');


const STORYLY_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NfaWQiOjU1NiwiYXBwX2lkIjoxMzg5LCJpbnNfaWQiOjE4NjY1fQ._PwkZ48JdHkSU01KUR2n66zJcL29JhykNTMRUorfvE4"

export default class App extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <View>
                <Storyly
                    style={{ width: '100%', height: '100%', marginTop: 10, backgroundColor: "#fe000000" }}
                    storylyId={STORYLY_TOKEN}
                    storyGroupSize="custom"
                    storyGroupListOrientation='vertical'
                    storyGroupViewFactory={{
                        width: convertToNative(Dimensions.get('window').width),
                        height: convertToNative(Dimensions.get('window').height) / 6,
                        customView: CustomPortraitView,
                    }}
                    onLoad={loadEvent => {
                        console.log(`[Storyly] default - onLoad`);
                    }} />
            </View>
        );
    }
}

const convertToNative = (size) => {
    return Platform.OS === 'android' ? PixelRatio.getPixelSizeForLayoutSize(size) : size
}


const CustomPortraitView = ({ storyGroup }) => {
    return (
        <>
        {(storyGroup ? (
            <View
                style={{
                    width: "100%",
                    height: "100%",
                    padding: 20,
                }} >
                <View
                    style={{
                        backgroundColor: '#fff',
                        borderRadius: 8,
                        padding: 15,
                        marginVertical: 8,
                        shadowColor: '#000',
                        shadowOffset: { width: 0, height: 2 },
                        shadowOpacity: 0.1,
                        shadowRadius: 4,
                        elevation: 2,
                    }}>
                    <View
                        style={{
                            flexDirection: 'row',
                            alignItems: 'center',
                        }}>
                        <Image
                            source={{ uri: storyGroup.iconUrl }}
                            style={{
                                width: 100,
                                height: 100,
                                borderRadius: 10,
                                marginRight: 15,
                            }}
                        />
                        <View>
                            <Text style={{
                                    fontSize: 18,
                                    fontWeight: 'bold',
                                    color: '#333',
                                    marginBottom: 5,
                                }}>{storyGroup.title}</Text>
                            <Text style={{
                                    fontSize: 14,
                                    color: '#666',
                                }}>SubTitleTest</Text>
                        </View>
                    </View>
                </View>
                </View>
            ) : (
                <View style={{ width: "100%", height: "100%", borderRadius: 8 }}></View>
            ))}
        </>
    )
}


const ShowHideAnimation = (props) => {
    const heightAnim = useRef(new Animated.Value(0)).current;

    useEffect(() => {
        Animated.timing(heightAnim, {
            toValue: props.isHidden ? 0 : props.style.height,
            duration: 500,
            useNativeDriver: false,
        }).start();
    }, [props.isHidden])

    return (
        <Animated.View style={{ height: heightAnim, overflow: 'hidden' }}>
            {props.children}
        </Animated.View>
    );
};
